#!/bin/bash
# Orchestreert LFS 12.4 hoofdstuk 8, binnen chroot als root.
# Zelfde schone root-omgeving als hoofdstuk 7; geen env.sh binnen chroot.
# Shadow vraagt interactief om het root-wachtwoord.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_DIR="/sources"

STEPS=(
  "01-man-pages.sh"
  "02-iana-etc.sh"
  "03-glibc.sh"
  "04-zlib.sh"
  "05-bzip2.sh"
  "06-xz.sh"
  "07-lz4.sh"
  "08-zstd.sh"
  "09-file.sh"
  "10-readline.sh"
  "11-m4.sh"
  "12-bc.sh"
  "13-flex.sh"
  "14-tcl.sh"
  "15-expect.sh"
  "16-dejagnu.sh"
  "17-pkgconf.sh"
  "18-binutils.sh"
  "19-gmp.sh"
  "20-mpfr.sh"
  "21-mpc.sh"
  "22-attr.sh"
  "23-acl.sh"
  "24-libcap.sh"
  "25-libxcrypt.sh"
  "26-shadow.sh"
  "27-gcc.sh"
  "28-ncurses.sh"
  "29-sed.sh"
  "30-psmisc.sh"
  "31-gettext.sh"
  "32-bison.sh"
  "33-grep.sh"
  "34-bash.sh"
  "35-libtool.sh"
  "36-gdbm.sh"
  "37-gperf.sh"
  "38-expat.sh"
  "39-inetutils.sh"
  "40-less.sh"
  "41-perl.sh"
  "42-xml-parser.sh"
  "43-intltool.sh"
  "44-autoconf.sh"
  "45-automake.sh"
  "46-openssl.sh"
  "47-libelf.sh"
  "48-libffi.sh"
  "49-python.sh"
  "50-flit-core.sh"
  "51-packaging.sh"
  "52-wheel.sh"
  "53-setuptools.sh"
  "54-ninja.sh"
  "55-meson.sh"
  "56-kmod.sh"
  "57-coreutils.sh"
  "58-diffutils.sh"
  "59-gawk.sh"
  "60-findutils.sh"
  "61-groff.sh"
  "62-grub.sh"
  "63-gzip.sh"
  "64-iproute2.sh"
  "65-kbd.sh"
  "66-libpipeline.sh"
  "67-make.sh"
  "68-patch.sh"
  "69-tar.sh"
  "70-texinfo.sh"
  "71-vim.sh"
  "72-markupsafe.sh"
  "73-jinja2.sh"
  "74-udev.sh"
  "75-man-db.sh"
  "76-procps-ng.sh"
  "77-util-linux.sh"
  "78-e2fsprogs.sh"
  "79-sysklogd.sh"
  "80-sysvinit.sh"
  "81-stripping.sh"
  "82-cleanup.sh"
)

for step in "${STEPS[@]}"; do
  echo "==> ---- (chroot ch8) $step ----"
  if bash "$SCRIPT_DIR/$step" 2>&1 | tee "$LOG_DIR/log-chroot-ch8-$step.txt"; then
    echo "==> $step geslaagd"
  else
    echo "==> $step MISLUKT — zie $LOG_DIR/log-chroot-ch8-$step.txt"
    exit 1
  fi
done

echo "==> Hoofdstuk 8 (binnen chroot) volledig doorlopen"
